apiVersion: v1
kind: Service
metadata:
  name: rollback-app-service
spec:
  selector:
    app: rollback-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080
